services:
  app:
    build: .
    container_name: mole-world-revolution
    command: uvicorn webapp.main:app --host 0.0.0.0 --port 8080 --reload --reload-include *
    ports:
      - 8080:8080
    volumes:
      - .:/app

